# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

        # Specify service dependencies here if necessary
        # CircleCI maintains a library of pre-built images
        # documented at https://circleci.com/docs/2.0/circleci-images/
        # - image: circleci/mongo:3.4.4
        environment:
          CODECOV_TOKEN: 5aade52f-653e-4539-aa00-137db7c15586

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: commitlint
          command: ./node_modules/.bin/commitlint --from HEAD~1 --to HEAD --verbose

      # run tests!
      # - run: npm test


      # TODO: Enforce eslint, commit message format, run coverage checks  
      # TODO: Add awesome_bot to check URLs in markdown files 
      # https://github.com/dkhamsing/awesome_bot
      # machine:
      #   ruby:
      #     version: 2.4.1
      # test:
      #   pre:
      #     - gem install awesome_bot
      #   override:
      #     - awesome_bot README.md