version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    environment:
      CODECOV_TOKEN: 5aade52f-653e-4539-aa00-137db7c15586
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run lint
          name: Lint code
      - run:
          command: ./node_modules/.bin/commitlint --from HEAD~1 --to HEAD --verbose
          name: Commit Linting
      - run:
          command: npm run test
          name: Run tests
      - persist_to_workspace:
          root: ~/repo
          paths: .

workflows:
  build_and_test_workflow:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore:
                - master
